Repository tessi-gdoc/blog-consulting-and-integration.tessi.eu, pull requests merged in 2021-05, with the labels that each got.

#489 Show toc option
  src/cms/preview-templates/BlogPostPreview.js
  src/data/posts/6-leviers-pour-capitaliser-sur-sa-solution-ccm/index_fr.md
  src/data/posts/archivage-records-management-quelles-differences/index_fr.md
  src/data/posts/case-management-par-ou-commencer/index_fr.md
  src/data/posts/coffre-fort-numerique-cas-utilisation-en-entreprise-et-guide-pour-choisir/index_fr.md
  src/data/posts/comment-maintenir-sa-ged-et-maintenir-son-plan-de-classement/index_fr.md
  src/data/posts/comment-passer-a-une-strategie-omnicanale/index_fr.md
  src/data/posts/connecteurs-api-web-service-jms-quel-interfacage-pour-logiciels-ged-ecm/index_fr.md
  src/data/posts/de-l-editique-aux-solutions-de-gestion-de-la-communication-client-quelles-evolutions-et-avantages-majeurs/index_fr.md
  src/data/posts/de-la-ged-au-case-management-pourquoi-changer/index_fr.md
  src/data/posts/de-la-monetique-aux-nouveaux-moyens-de-paiements/index_fr.md
  src/data/posts/dematerialisation-le-guide-complet/index_fr.md
  src/data/posts/editique-3-processus-de-traitement-des-communications-client/index_fr.md
  src/data/posts/editique-definition-role-enjeux/index_fr.md
  src/data/posts/editique_marketing_deux_mondes_a_rassembler/index_fr.md
  src/data/posts/ged-ecm-gestion-de-contenu/index_fr.md
  src/data/posts/introduction-progressive-web-apps-avantages-exemple-tuto/index_fr.md
  src/data/posts/judith-granat-retraites-populaires-l-experience-client-un-sujet-large-transverse-et-multicanal/index_fr.md
  src/data/posts/l-ecm-en-route-vers-les-content-services-gerer-ses-contenus-autrement/index_fr.md
  src/data/posts/laurent-leterrier-bnpp-le-secteur-des-paiements-agite-par-le-foisonnement-des-usages/index_fr.md
  src/data/posts/le-case-management-objectif-no-code/index_fr.md
  src/data/posts/multicanal_cross_canal_omnicanal_quelle_strategie_communication/index_fr.md
  src/data/posts/pourquoi-comment-developper-l-engagement-collaborateur/index_fr.md
  src/data/posts/records-management-transparence-gestion-documentaire/index_fr.md
  src/data/posts/reinventer_ses_processus_metier/image_reinventer_ses_processus_metier.png
  src/data/posts/reinventer_ses_processus_metier/index_fr.md
  src/data/posts/sae-systeme-archivage-electronique-enjeux-mise-en-oeuvre/index_fr.md
  src/data/posts/solution-de-case-management-comment-bien-realiser-son-benchmark/index_fr.md
  src/data/posts/solutions-ged-ecm-5-bonnes-raisons-integrer-technologies-ia-rpa/index_fr.md
  src/data/posts/strategie_omnicanale_et_experience_client_deux_notions_intimement_liees/index_fr.md
  src/templates/blog-post.js
  static/admin/config.yml
Labels: enhancement

#488 chore: :rocket: emmanuel-de-ternay-bpmn-cmmn-methodologie-processus-metiers/index_fr
  src/data/posts/emmanuel-de-ternay-bpmn-cmmn-methodologie-processus-metiers/image_bpmn_cmmn_interview_emmanuel-de-ternay.png
  src/data/posts/emmanuel-de-ternay-bpmn-cmmn-methodologie-processus-metiers/index_fr.md
Labels: netlify-cms/pending_publish

#490 chore: :speech_balloon: emmanuel-de-ternay-bpmn-cmmn-methodologie-processus-metiers/index_fr
  src/data/posts/emmanuel-de-ternay-bpmn-cmmn-methodologie-processus-metiers/index_fr.md
Labels: netlify-cms/pending_publish

#491 Fix embed videos
  src/cms/cms.js
  src/data/posts/solutions-ged-ecm-5-bonnes-raisons-integrer-technologies-ia-rpa/index_fr.md
Labels: bug

#492 NetlifyCMS YT Widget : fix swapped id and title (pattern)
  src/cms/cms.js
Labels: bug
